spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
logging:
  level:
    root: INFO
    com.example.springclient.controller: DEBUG
    com.example.springclient.service: DEBUG